# Install versions of Node and Yarn required by build pipelines.
steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'
    displayName: 'Install Node.js'

  - script: |
      npm i -g yarn@1
    displayName: 'Install yarn'
