# Install versions of Node and Yarn required by build pipelines.
steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - task: geeklearningio.gl-vsts-tasks-yarn.yarn-installer-task.YarnInstaller@3
    displayName: 'Use Yarn 1.19.x'
    inputs:
      versionSpec: 1.19.x
      checkLatest: true
      includePrerelease: false

  - task: Cache@2
    inputs:
      key: 'node_modules | $(Agent.OS) | yarn.lock'
      restoreKeys: |
        node_modules | $(Agent.OS)
        node_modules
      path: node_modules
    displayName: Cache node_modules

  - script: yarn --frozen-lockfile
    displayName: Yarn
