variables:
  deployBasePath: 'pr-deploy-site/$(Build.SourceBranch)'

  deployHost: 'fabricweb.z5.web.core.windows.net'

  ${{ if ne(variables['Build.SourceBranch'], 'refs/heads/7.0') }}:
    targetBranch: 'origin/$(System.PullRequest.TargetBranch)'
