variables:
  deployBasePath: 'pr-deploy-site/$(Build.SourceBranch)'

  deployHost: 'fabricweb.z5.web.core.windows.net'

  # Note that this subscription only has access to the fluentuipr storage account
  azureSubscription: 'Azure PR deploy'

  ${{ if ne(variables['Build.SourceBranch'], 'refs/heads/7.0') }}:
    targetBranch: 'origin/$(System.PullRequest.TargetBranch)'
