variables:
  # Also accessed as process.env.DEPLOYHOST
  deployHost: 'fluentuipr.z22.web.core.windows.net'

  # Also accessed as process.env.DEPLOYURL
  deployUrl: 'https://$(deployHost)/$(deployBasePath)'

  # This service principal ("subscription" is a misleading name) only has access to the fluentuipr storage account
  azureSubscription: Azure PR deploy
  azureStorage: fluentuipr

  ${{ if not(startsWith(variables['Build.SourceBranch'], 'refs/heads/')) }}:
    targetBranch: 'origin/$(System.PullRequest.TargetBranch)'
    # Deploy PRs under "pull/####"
    deployBasePath: 'pull/$(System.PullRequest.PullRequestNumber)'
  ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads/') }}:
    targetBranch: ''
    # Deploy 7.0 under "heads/branchname"
    deployBasePath: ${{ replace(variables['Build.SourceBranch'], 'refs/', '')) }}
