language: node_js
node_js:
  - 'node'
before_script:
  - if [[ `npm -v` != 5* ]]; then npm i -g npm@5; fi
  - npm install -g gulp
script:
  - npm run build
cache:
  directories:
    - node_modules
    - common/node_modules
