language: node_js
node_js:
- '7'
before_script:
- npm install -g gulp
script:
- node vrtDeploy --user 'fabricreact\fabricreact' --password $FTP_PASSWORD --pull $TRAVIS_PULL_REQUEST
after_success: node vrtDeploy --user 'fabricreact\fabricreact' --password $FTP_PASSWORD --pull $TRAVIS_PULL_REQUEST
