pr: none

trigger: none

variables:
  - group: fabric-variables

pool:
  vmImage: 'Ubuntu 16.04'

jobs:
  - job: Build
    pool: 'Self Host Ubuntu'
    steps:
      - script: |
          pwd
          whoami
          date
          ps -ef
          who
          df -h
          touch /testing.123
        displayName: yarn
