pr:
  - master

trigger:
  - master

variables:
  - group: fabric-variables
  - template: .devops/templates/variables.yml
    parameters:
      pathPrefix: SourceVersion

pool: 'Self Host Ubuntu'

jobs:
  - job: ScreenerFluent
    workspace:
      clean: all
    steps:
      - template: .devops/templates/tools.yml

      - task: Bash@3
        inputs:
          filePath: yarn-ci.sh
        displayName: yarn

      - script: yarn workspace @fluentui/docs vr:build
        displayName: build FUI N* VR Test

      - task: AzureUpload@2
        displayName: Upload N* doc site
        inputs:
          azureSubscription: $(azureSubscription)
          BlobPrefix: '$(deployBasePath)/react-northstar'
          CacheControl: 'public, max-age=600000'
          ContainerName: '$web'
          SourcePath: 'packages/fluentui/docs/dist'
          storage: fabricweb

      - script: yarn workspace @fluentui/docs vr:test
        displayName: start FUI N* VR Test
        env:
          SCREENER_API_KEY: $(screener.key)

      - template: .devops/templates/cleanup.yml

  - job: Screener
    workspace:
      clean: all
    steps:
      - template: .devops/templates/tools.yml

      - task: Bash@3
        inputs:
          filePath: yarn-ci.sh
        displayName: yarn

      - script: |
          for i in {1..1000000}
          do
            echo "$i - Testing console log output Testing console log output Testing console log output Testing console log output Testing console log output "
          done
        displayName: run VR Test
        env:
          SCREENER_API_KEY: $(screener.key)
          BACKFILL_CACHE_PROVIDER: $(backfillProvider)
          BACKFILL_CACHE_PROVIDER_OPTIONS: $(backfillOptions)

      - template: .devops/templates/cleanup.yml
