pr:
  - 7.0

trigger: none

variables:
  - group: fabric-variables

pool: 'Self Host Ubuntu'

workspace:
  clean: all

steps:
  - template: .devops/templates/tools.yml

  - script: |
      npx midgard-yarn install
    displayName: yarn

  # @fluentui/perf-test needs build and bundle steps
  - script: |
      yarn lage build --to @fluentui/perf-test --to perf-test --verbose --no-cache --grouped
    displayName: build  @fluentui v0
    env:
      BACKFILL_CACHE_PROVIDER: 'azure-blob'
      BACKFILL_CACHE_PROVIDER_OPTIONS: '{"connectionString":"$(BACKFILL_CONNECTION_STRING)", "container":"$(BACKFILL_CONTAINER)"}'

  # Fabric: perf-test will build, bundle, and run-perftest
  - script: |
      yarn just perf-test
    workingDirectory: apps/perf-test
    displayName: Perf Test

  - task: AzureUpload@2
    displayName: Upload Perf Test Result to PR deploy site
    inputs:
      SourcePath: 'apps/perf-test/dist'
      azureSubscription: 'UI Fabric (bac044cf-49e1-4843-8dda-1ce9662606c8)'
      storage: fabricweb
      ContainerName: '$web'
      BlobPrefix: 'pr-deploy-site/$(Build.SourceBranch)/perf-test'

  - task: GithubPRComment@0
    displayName: 'Post Perf Results to Github Pull Request'
    inputs:
      githubOwner: microsoft
      githubRepo: 'fluentui'
      blobFilePath: '$(Build.SourcesDirectory)/$(PerfCommentFilePath)'
      status: '$(PerfCommentStatus)'
      uniqueId: 'perfComment9423'

  - script: |
      yarn stats:build
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/7.0')
    displayName: Bundle Statistics (7.0 only)

  - script: |
      yarn perf
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/7.0')
    displayName: Performance Tests (7.0 only)

  - template: .devops/templates/cleanup.yml
