pr:
  - master

trigger: none

variables:
  - group: fabric-variables

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: ms.vss-keros-publishTestResultTask.KerosQueuePublishTestResultJobTask.Publish Accessibility Check Results@0
  displayName: 'Publish Accessibility Check Results'
  inputs:
    threshold: 40
    searchfolder: '$(Agent.BuildDirectory)/apps/a11y-tests/src/tests/sarif/'
- task: PublishTestResults@2
  displayName: 'Publish Test Results **/WDIO*.xml'
  inputs:
    testResultsFiles: '**/WDIO*.xml'

