pr: none
trigger: none

pool:
  vmImage: 'Ubuntu 16.04'

steps:
  - checkout: self
    persistCredentials: true

  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: |
      yarn
    displayName: yarn

  - script: |
      yarn build --min
    displayName: build (no test or lint)

  - script: |
      yarn update-snapshots
    displayName: update snapshots

  - script: |
      git config --global user.email "fabrictactical@microsoft.com"
      git config --global user.name "Fabric Tactical"
    displayName: Set up git config user name and email

  - script: |
      if [ -n "$(git status --porcelain | grep -E "(\.snap|\.shot)" ]; then
        git remote add target_remote $(remote)
        git fetch target_remote
        git checkout -b -t target_remote/$(branchName) target_branch
        git add *.shot *.snap
        git commit -m "updated snapshots"
        yarn change -m "updated snapshots" --type patch
        git push target_remote target_branch
      fi
    displayName: push changes back
