parameters:
  artifact: ''

# Download and extract build artifacts
steps:
  - task: DownloadPipelineArtifact@2
    inputs:
      source: 'specific' # Options: current, specific
      project: cd9e4e13-b8db-429a-9c21-499bf1c98639
      pipeline: 84
      artifact: ${{ parameters.artifact }}

  - task: ExtractFiles@1
    inputs:
      # By default, input patterns start in the root folder of the repo (same as if you had specified $(Build.SourcesDirectory)).
      # It'd be nice to use path variables here, but this task's inputs use relative pathing.
      # Artifacts are downloaded by named directories into $(Pipeline.Workspace) by default, which is one directory up.
      archiveFilePatterns: '../Build/*.tar.gz'
      # Extract into $(Pipeline.Workspace). Archive should include root folder so that contents get extracted into proper subdirectories.
      destinationFolder: '..'
      cleanDestinationFolder: false
