pr:
  - master

trigger:
  - master

variables:
  - group: fabric-variables

pool:
  vmImage: 'Ubuntu 16.04'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '8.x'
    displayName: 'Install Node.js'

  - script: |
      npm install -- --bypass-policy
    displayName: rush install

  - script: |
      npm run checkchange
    displayName: check change

  - script: |
      npm run buildci
    displayName: build ci

  - script: |
      npm run bundlesize
    displayName: check bundle size

  - script: |
      npm run vrtest
    displayName: run VR Test
    env:
      SCREENER_API_KEY: $(screener.key)
