pr:
  - master

trigger:
  - master

jobs:
  - job: build_react
    timeoutInMinutes: 75
    pool:
      vmImage: 'windows-2019'
    steps:
      - template: .devops/templates/tools.yml

      - script: npx midgard-yarn install
        displayName: yarn

      - script: yarn build --to @fluentui/react @fluentui/react-button @fluentui/react-compose @fluentui/keyboard-key --no-cache
        displayName: yarn build to @fluentui/react

      - script: yarn workspace test-bundles bundle:size
        displayName: yarn bundle test-bundles
        env:
          PACKAGE: '@fluentui/react'

      - script: yarn bundlesizecollect
        displayName: 'Collate Bundle Size Information'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Bundle Size information to Azure Dev Ops Artifacts'
        inputs:
          PathtoPublish: 'apps/test-bundles/dist/bundlesize.json'
          ArtifactName: bundlesize-react

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact dist folder upon build for debug'
        inputs:
          PathtoPublish: 'apps/test-bundles/dist'
          ArtifactName: distdrop-react

  - job: build_northstar
    timeoutInMinutes: 75
    pool:
      vmImage: 'windows-2019'
    steps:
      - template: .devops/templates/tools.yml

      - script: npx midgard-yarn install
        displayName: yarn

      - script: yarn build --to @fluentui/react-northstar --no-cache
        displayName: yarn build to @fluentui/react-northstar

      - script: yarn workspace test-bundles bundle:size
        displayName: yarn bundle test-bundles
        env:
          PACKAGE: '@fluentui/react-northstar'

      - script: yarn bundlesizecollect
        displayName: 'Collate Bundle Size Information'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Bundle Size information to Azure Dev Ops Artifacts'
        inputs:
          PathtoPublish: 'apps/test-bundles/dist/bundlesize.json'
          ArtifactName: bundlesize-northstar

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact dist folder upon build for debug'
        inputs:
          PathtoPublish: 'apps/test-bundles/dist'
          ArtifactName: distdrop-northstar

  - job: merge
    pool:
      vmImage: 'windows-2019'
    dependsOn:
      - build_react
      - build_northstar
    steps:
      - task: DownloadPipelineArtifact@2
        displayName: 'Download Pipeline Artifact'
        inputs:
          buildType: specific
          project: 'fabricpublic'
          definition: 55
          buildVersionToDownload: specific
          pipelineId: 186534
          downloadType: single
          artifactName: bundlesizes.json
          targetPath: '$(Build.ArtifactStagingDirectory)'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: bundlesizes.json'
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)/bundlesizes.json'
          ArtifactName: bundlesizes.json

  - job: lightrail
    pool: server
    dependsOn:
      - merge
    steps:
      - task: odefun.odsp-lightrail-tasks-partner.odsp-lightrail-tasks-SizeAuditorWorker.SizeAuditorWorker@0
        displayName: 'Size Auditor Check on LightRail'
        inputs:
          connectedServiceName: lowimpact
          sourceVersionMessage: '$(Build.SourceVersionMessage)'
          sourceRepositoryUrl: 'https://github.com/microsoft/fluentui'
