pr:
  - master

trigger:
  - master

variables:
  - group: fabric-variables

pool:
  vmImage: 'Ubuntu 16.04'

stages:
  - stage: Build
    pool: 'Self Host Ubuntu'
    jobs:
      - job: BuildJob
        steps:
          - template: azure-pipelines.tools.yml

          - script: |
              yarn
            displayName: yarn

          - script: |
              yarn checkchange
            displayName: check change

          - script: |
              yarn build
            displayName: build

          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: $(Build.Repository.LocalPath)
              # Include root folder so archive can just be extracted into $(Pipeline.Workspace)
              includeRootFolder: true
              archiveType: 'tar'
              tarCompression: 'gz'
              archiveFile: $(Build.ArtifactStagingDirectory)/build.tar.gz
              replaceExistingArchive: true

          - publish: $(Build.ArtifactStagingDirectory)
            artifact: Build-PR-$(Build.BuildNumber)

          - script: az --version
            displayName: 'Show Azure CLI version'

          - script: az extension add -n azure-devops
            displayName: 'Install Azure DevOps Extension'

          - script: |
              echo $(buildQueuePat) | az devops login --organization https://uifabric.visualstudio.com
              az devops configure --defaults organization=https://uifabric.visualstudio.com project="fabricpublic" --use-git-aliases true
              az pipelines build queue --verbose --org https://uifabric.visualstudio.com -p fabricpublic --definition-name "office-ui-fabric-react - Perf-Test" --branch $(Build.SourceBranch) --commit-id $(Build.SourceVersion) --variables artifact=Build-PR-$(Build.BuildNumber) buildId=$(Build.BuildId)
              az pipelines build queue --verbose --org https://uifabric.visualstudio.com -p fabricpublic --definition-name "office-ui-fabric-react - Screener" --branch $(Build.SourceBranch) --commit-id $(Build.SourceVersion) --variables artifact=Build-PR-$(Build.BuildNumber) buildId=$(Build.BuildId)
            env:
              AZURE_DEVOPS_EXT_PAT: $(buildQueuePat)
            displayName: Trigger Perf-Test and Screener jobs

          - task: DeleteFiles@1
            inputs:
              SourceFolder: $(Build.SourcesDirectory)
              Contents: '**/*'

  - stage: Validate
    dependsOn: Build
    pool: 'Self Host Ubuntu'
    jobs:
      - job: ValidateJob
        steps:
          # No need for checkout since we're using build artifacts.
          - checkout: none
          - template: azure-pipelines.artifacts.yml
            parameters:
              artifact: Build-PR-$(Build.BuildNumber)

          - script: |
              yarn test
            displayName: test

          - script: |
              yarn lint
            displayName: lint

          - script: |
              yarn check-for-changed-files
            displayName: check for changed files

          - task: DeleteFiles@1
            inputs:
              SourceFolder: $(Build.SourcesDirectory)
              Contents: '**/*'

  - stage: Deploy
    dependsOn: Build
    pool: 'Self Host Ubuntu'

    jobs:
      - job: DeployJob
        steps:
          # No need for checkout since we're using build artifacts.
          - checkout: none
          - template: azure-pipelines.artifacts.yml
            parameters:
              artifact: Build-PR-$(Build.BuildNumber)

          - template: azure-pipelines.tools.yml

          - script: |
              yarn bundle
            displayName: bundle

          - task: AzureUpload@1
            displayName: Upload PR deploy site
            inputs:
              SourcePath: 'apps/pr-deploy-site/dist'
              azureSubscription: 'UI Fabric (bac044cf-49e1-4843-8dda-1ce9662606c8)'
              storage: fabricweb
              ContainerName: '$web'
              BlobPrefix: 'pr-deploy-site/$(Build.SourceBranch)'

          - task: DeleteFiles@1
            inputs:
              SourceFolder: $(Build.SourcesDirectory)
              Contents: '**/*'
