pr:
  - 5.0

# There's a separate pipeline for CI which also uses this file, but with a trigger override in the UI
# https://dev.azure.com/uifabric/fabricpublic/_apps/hub/ms.vss-ciworkflow.build-ci-hub?_a=edit-build-definition&id=164&view=Tab_Triggers
trigger: none

variables:
  - group: fabric-variables

pool: 'Self Host Ubuntu'

workspace:
  clean: all

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '8.x'
    displayName: 'Install Node.js'

  - script: |
      npm install --ignore-scripts
      node node_modules/@microsoft/rush/bin/rush install --bypass-policy
    displayName: rush install

  - script: |
      npm run checkchange
    displayName: check change

  - script: |
      npm run buildfast
    displayName: build ci

  - script: |
      npm run vrtest
    displayName: run VR Test
    env:
      SCREENER_API_KEY: $(screener.key)

  # In theory the "workspace: clean: all" setting should handle this, but it doesn't always seem to work.
  # ReallyClean is a custom task from our internal UI Fabric azure-devops-tasks repo which attempts to
  # delete the given directory with multiple retries.
  - task: ReallyClean@0
    inputs:
      directory: $(Agent.BuildDirectory)
    condition: always()