jobs:
  - job: build
    pool:
      name: Hosted VS2017
      demands: npm
    steps:
      - scripts: yarn
        displayName: yarn

      - scripts: yarn build
        displayName: yarn build

      - task: Npm@1
        displayName: 'Collate Bundle Size Information'
        inputs:
          command: custom
          workingDir: .
          verbose: false
          customCommand: 'run bundlesizecollect'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Bundle Size information to Azure Dev Ops Artifacts'
        inputs:
          PathtoPublish: 'apps/test-bundles/dist/bundlesizes.json'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact ActivityItem stats.json file for comparing performance'
        inputs:
          PathtoPublish: 'apps/test-bundles/dist/office-ui-fabric-react-ActivityItem.stats.json'
          ArtifactName: activityitemstatsdrop

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact dist folder upon build for debug'
        inputs:
          PathtoPublish: 'apps/test-bundles/dist'
          ArtifactName: distdrop

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact office-ui-fabric-react.js from dist folder'
        inputs:
          PathtoPublish: 'packages/office-ui-fabric-react/dist/office-ui-fabric-react.js'
          ArtifactName: oufrdrop

  - job: lightrail
    pool: server
    dependsOn: build
    steps:
      - task: odefun.odsp-lightrail-tasks-partner.odsp-lightrail-tasks-SizeAuditorWorker.SizeAuditorWorker@0
        displayName: 'Size Auditor Check on LightRail'
        inputs:
          connectedServiceName: lowimpact
          sourceVersionMessage: '$(Build.SourceVersionMessage)'
          sizeTolerance: 1024
