pr:
  - master

trigger:
  - master

jobs:
  - job: build-react
    timeoutInMinutes: 75
    pool:
      vmImage: 'windows-2019'
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '12.x'
        displayName: 'Install Node.js'

      - script: npx midgard-yarn install
        displayName: yarn

      - script: yarn build --to @fluentui/react @fluentui/react-button @fluentui/react-compose --no-cache
        displayName: yarn build to @fluentui/react

      - script: PACKAGE=@fluentui/react yarn workspace test-bundles bundle:size
        displayName: yarn bundle test-bundles

      - script: yarn bundlesizecollect
        displayName: 'Collate Bundle Size Information'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Bundle Size information to Azure Dev Ops Artifacts'
        inputs:
          PathtoPublish: 'apps/test-bundles/dist/bundlesizes.json'
          ArtifactName: bundlesizes-react

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact dist folder upon build for debug'
        inputs:
          PathtoPublish: 'apps/test-bundles/dist'
          ArtifactName: distdrop-react

  - job: build-northstar
    timeoutInMinutes: 75
    pool:
      vmImage: 'windows-2019'
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '12.x'
        displayName: 'Install Node.js'

      - script: npx midgard-yarn install
        displayName: yarn

      - script: yarn build --to @fluentui/react-northstar --no-cache
        displayName: yarn build to @fluentui/react-northstar

      - script: PACKAGE=@fluentui/react-northstar yarn workspace test-bundles bundle:size
        displayName: yarn bundle test-bundles

      - script: yarn bundlesizecollect
        displayName: 'Collate Bundle Size Information'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Bundle Size information to Azure Dev Ops Artifacts'
        inputs:
          PathtoPublish: 'apps/test-bundles/dist/bundlesizes.json'
          ArtifactName: bundlesizes-northstar

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact dist folder upon build for debug'
        inputs:
          PathtoPublish: 'apps/test-bundles/dist'
          ArtifactName: distdrop-northstar

  - job: lightrail
    pool: server
    dependsOn: build
    steps:
      - task: odefun.odsp-lightrail-tasks-partner.odsp-lightrail-tasks-SizeAuditorWorker.SizeAuditorWorker@0
        displayName: 'Size Auditor Check on LightRail'
        inputs:
          connectedServiceName: lowimpact
          sourceVersionMessage: '$(Build.SourceVersionMessage)'
          sourceRepositoryUrl: 'https://github.com/microsoft/fluentui'
