pr:
  - master

trigger:
  - master

variables:
  - group: fabric-variables

pool: 'Self Host Ubuntu'

jobs:
  - job: Build
    steps:
      - script: |
          yarn
        displayName: yarn

      - script: |
          yarn bump
        displayName: bump

      - script: |
          cat packages/fluentui/code-sandbox/package.json
        displayName: cat code-sandbox package.json
