pr: none
trigger: none

# Customize build number to include major version
# Example: v5_20190626.1
name: 'v5_$(Date:yyyyMMdd)$(Rev:.r)'

variables:
  - group: 'Github and NPM secrets'

pool:
  vmImage: 'Ubuntu 20.04'

schedules:
# minute 0, hour 11 in UTC (4am in UTC+7), any day of month, any month, days 1-5 of week (M-F)
# https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?tabs=yaml&view=azure-devops#supported-cron-syntax
- cron: '0 11 * * 1-5'
  displayName: 'Daily release (M-F at 4am)' # will be 3am when DST ends unless trigger is updated
  branches:
    include:
      - 5.0

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "8.x"
    displayName: "Install Node.js"

  - script: |
      git config user.name "UI Fabric Build"
      git config user.email "fluentui-internal@service.microsoft.com"
      git remote set-url origin https://$(githubUser):$(githubPAT)@github.com/microsoft/fluentui.git
    displayName: Authenticate git for pushes

  - script: |
      npm install --ignore-scripts
      node node_modules/@microsoft/rush/bin/rush install --bypass-policy
    displayName: rush install

  - script: |
      npm run build
    displayName: rush build (Create production build)

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: apps/fabric-website/dist
      artifactName: "fabric-website"
      publishLocation: "Container"
    displayName: "Publish Artifact: Fabric Website"

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: packages/office-ui-fabric-react/dist
      artifactName: "fabric"
      publishLocation: "Container"
    displayName: "Publish Artifact: Fabric"

  - script: |
      node node_modules/@microsoft/rush/bin/rush publish -a -p -b 5.0 -t lts-5 -n $(npmToken) --add-commit-details
    displayName: "Publish Change Requests and Bump Versions"

  - script: |
      node scripts/updateReleaseNotes.js --token=$(githubPAT) --apply --debug
    displayName: "Update github release notes"

  - script: |
      npm run create-public-flight-config -- --baseCDNUrl https://fabricweb.azureedge.net/fabric-website/$(Build.BuildNumber)/
    workingDirectory: apps/fabric-website
    displayName: "Generate Fabric Website Flight Manifest Files"

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: apps/fabric-website/flights
      artifactName: "fabric-website-manifests"
      publishLocation: "Container"
    displayName: "Publish Artifact: Website manifests"
