pr:
  - master
  - website-content

trigger:
  - master

variables:
  - group: fabric-variables

pool: 'Self Host Ubuntu'

jobs:
  - job: Validation
    workspace:
      clean: all
    steps:
      - template: azure-pipelines.tools.yml

      - script: |
          yarn
        displayName: yarn

      - script: |
          yarn checkchange
        displayName: check change

  - job: BuildTest
    workspace:
      clean: all
    steps:
      - template: azure-pipelines.tools.yml

      - script: |
          yarn
        displayName: yarn

      - template: .devops/templates/pr-target-branch.yml

      - script: |
          yarn lage build test lint --since $(target_branch) --verbose
        displayName: build, test, lint
        env:
          BACKFILL_CACHE_PROVIDER: 'azure-blob'
          BACKFILL_CACHE_PROVIDER_OPTIONS: '{"connectionString":"$(BACKFILL_CONNECTION_STRING)", "container":"$(BACKFILL_CONTAINER)"}'

      - script: |
          az --version
          az extension add -n azure-devops
          echo $(buildQueuePat) | az devops login --organization https://dev.azure.com/uifabric
          az devops configure --defaults organization=https://dev.azure.com/uifabric project="fabricpublic" --use-git-aliases true
        env:
          AZURE_DEVOPS_EXT_PAT: $(buildQueuePat)
        displayName: Set up Azure CLI with DevOps

      - script: |
          az pipelines build queue --verbose --org https://dev.azure.com/uifabric -p fabricpublic --definition-name "Fluent UI React - Perf-Test" --branch $(Build.SourceBranch) --variables artifact=Build-PR-$(Build.BuildNumber) buildId=$(Build.BuildId) buildReason=$(Build.Reason)
        env:
          AZURE_DEVOPS_EXT_PAT: $(buildQueuePat)
        displayName: Trigger Perf-Test and Screener jobs

  - job: ValidateFluent
    workspace:
      clean: all
    steps:
      - template: azure-pipelines.tools.yml

      - script: |
          yarn
        displayName: yarn

      - template: .devops/templates/pr-target-branch.yml

      - script: |
          if [ $BUILD_REASON == "PullRequest" ]; then
            yarn danger ci
          else
            echo "Skipping Danger JS because BUILD_REASON ${BUILD_REASON} != PullRequest"
          fi
        displayName: danger
        env:
          DANGER_GITHUB_API_TOKEN: $(DANGER_GITHUB_API_TOKEN)

      - script: |
          yarn lage build --since $(target_branch) --scope @fluentui/* --no-deps --verbose
        displayName: build, test, lint
        env:
          BACKFILL_CACHE_PROVIDER: 'azure-blob'
          BACKFILL_CACHE_PROVIDER_OPTIONS: '{"connectionString":"$(BACKFILL_CONNECTION_STRING)", "container":"$(BACKFILL_CONTAINER)"}'

      - script: |
          yarn test:fluentui:e2e
        displayName: E2E Tests

      - script: |
          yarn test:fluentui:projects
        displayName: Project Tests

      - script: |
          yarn test:fluentui:circulars
        displayName: Circular Dependencies Tests

      - script: |
          yarn check-for-changed-files
        displayName: check for changed files

  - job: Deploy
    workspace:
      clean: all
    variables:
      PR_DEPLOY: 1
    steps:
      - template: azure-pipelines.tools.yml

      - script: |
          yarn
        displayName: yarn

      - template: .devops/templates/pr-target-branch.yml

      - script: |
          yarn lage bundle --since $(target_branch) --no-deps --verbose
        displayName: bundle
        env:
          BACKFILL_CACHE_PROVIDER: 'azure-blob'
          BACKFILL_CACHE_PROVIDER_OPTIONS: '{"connectionString":"$(BACKFILL_CONNECTION_STRING)", "container":"$(BACKFILL_CONTAINER)"}'

      - task: AzureUpload@1
        displayName: Upload PR deploy site
        inputs:
          SourcePath: 'apps/pr-deploy-site/dist'
          azureSubscription: 'UI Fabric (bac044cf-49e1-4843-8dda-1ce9662606c8)'
          storage: fabricweb
          ContainerName: '$web'
          BlobPrefix: 'pr-deploy-site/$(Build.SourceBranch)'

  - job: ScreenerFluent
    steps:
      - script: |
          yarn
        displayName: yarn

      - template: azure-pipelines.tools.yml

      - script: |
          git config --global user.email "fabrictactical@microsoft.com"
          git config --global user.name "Fabric Tactical"
          yarn test:fluentui:visual
        displayName: run FUI VR Test
        env:
          SCREENER_API_KEY: $(screener.key)

      - task: DeleteFiles@1
        inputs:
          SourceFolder: $(Build.SourcesDirectory)
          Contents: '**/*'
        condition: always()

  - job: Screener
    workspace:
      clean: all
    steps:
      - script: |
          yarn
        displayName: yarn

      - template: azure-pipelines.tools.yml

      - template: .devops/templates/pr-target-branch.yml

      - script: |
          git config --global user.email "fabrictactical@microsoft.com"
          git config --global user.name "Fabric Tactical"
        displayName: config git user and email

      - script: |
          yarn lage vrtest --debug --since $(target_branch) --no-deps --verbose
        displayName: run VR Test
        env:
          SCREENER_API_KEY: $(screener.key)
          BACKFILL_CACHE_PROVIDER: 'azure-blob'
          BACKFILL_CACHE_PROVIDER_OPTIONS: '{"connectionString":"$(BACKFILL_CONNECTION_STRING)", "container":"$(BACKFILL_CONTAINER)"}'
