name: Publish dep-graph

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  mention-to-teams:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Run nx dep-graph
        run: yarn nx affected:dep-graph --file=tmp/dep-graph/index.html
